export function InterviewReport({ session }) {
  if (!session) return null;

  const handlePrint = () => window.print();

  return (
    <div className="interview-report print-only-full">
      <div className="report-header">
        <h1>Interview Practice Report</h1>
        <div className="report-meta">
          <p><strong>University:</strong> {session.target_university}</p>
          {session.target_program && <p><strong>Program:</strong> {session.target_program}</p>}
          <p><strong>Date:</strong> {new Date(session.started_at).toLocaleDateString()}</p>
          {session.mode && <p><strong>Mode:</strong> {session.mode}</p>}
          {session.overall_score != null && (
            <p><strong>Overall Score:</strong> {session.overall_score.toFixed(1)}/10</p>
          )}
        </div>
      </div>

      {session.summary_feedback && (
        <div className="report-section">
          <h2>Summary</h2>
          <p>{session.summary_feedback}</p>
        </div>
      )}

      {session.exchanges?.length > 0 && (
        <div className="report-section">
          <h2>Question & Answer Breakdown</h2>
          {session.exchanges.map((ex, i) => (
            <div key={i} className="report-exchange">
              <h3>
                Question {ex.question_number}
                {ex.question_type && ` (${ex.question_type})`}
              </h3>
              <p className="report-question">{ex.question_text}</p>
              {ex.answer_text && (
                <>
                  <p><strong>Your Answer:</strong></p>
                  <p className="report-answer">{ex.answer_text}</p>
                </>
              )}
              {ex.content_score != null && (
                <div className="report-scores">
                  Content: {ex.content_score}/10 | Relevance: {ex.relevance_score}/10 | Clarity: {ex.clarity_score}/10
                  {ex.values_alignment_score != null && ` | Values: ${ex.values_alignment_score}/10`}
                  {ex.self_awareness_score != null && ` | Self-Awareness: ${ex.self_awareness_score}/10`}
                </div>
              )}
              {ex.feedback && <p className="report-feedback"><em>{ex.feedback}</em></p>}
            </div>
          ))}
        </div>
      )}

      <div className="report-footer">
        <p>Generated by Interview Tester — AI-powered admission interview preparation</p>
      </div>

      <button className="btn btn-primary no-print" onClick={handlePrint}>
        Print / Save as PDF
      </button>
    </div>
  );
}
